export const elements = {
    welcomeScreen: document.getElementById('welcome-screen'),
    welcomeSkipButton: document.getElementById('welcome-skip-btn'),
    authGate: document.getElementById('auth-gate'),
    appShell: document.getElementById('app-shell'),
    topNav: document.getElementById('top-nav'),
    gerarJogosButton: document.getElementById('gerar-jogos'),
    visualizarHistoricoButton: document.getElementById('visualizar-historico'),
    loadingMessage: document.getElementById('loading-message'),
    errorMessage: document.getElementById('error-message'),
    errorMessageText: document.getElementById('error-message-text'),
    errorCloseButton: document.getElementById('error-close-btn'),
    lotterySelect: document.getElementById('lottery-select'),
    numGamesInput: document.getElementById('num-games-input'),
    historicoArquivosContainer: document.getElementById('historico-arquivos-container-modal'),
    historicoArquivosLista: document.getElementById('historico-arquivos-lista-modal'),
    historicoConteudoContainer: document.getElementById('historico-conteudo-container-modal'),
    historicoConteudoJogosWrapper: document.getElementById('historico-conteudo-jogos-wrapper-modal'),
    currentFilenameSpan: document.getElementById('current-filename-modal'),
    voltarHistoricoButton: document.getElementById('voltar-historico-modal'),
    assistenciaBtn: document.getElementById('assistencia-btn'),
    hotNumbersList: document.getElementById('hot-numbers-list-modal'),
    coldNumbersList: document.getElementById('cold-numbers-list-modal'),
    limparHistoricoBtn: document.getElementById('limpar-historico-btn'),
    limparHistoricoDiretoBtn: document.getElementById('limpar-historico-direto-btn-modal'),
    customConfirmModal: document.getElementById('custom-confirm-modal'),
    modalTitle: document.getElementById('modal-title'),
    modalMessage: document.getElementById('modal-message'),
    modalConfirmBtn: document.getElementById('modal-confirm-btn'),
    modalCancelBtn: document.getElementById('modal-cancel-btn'),
    successModal: document.getElementById('success-modal'),
    successModalMessage: document.getElementById('success-modal-message'),
    themeToggle: document.getElementById('theme-toggle'),
    increaseFontButton: document.getElementById('increase-font'),
    decreaseFontButton: document.getElementById('decrease-font'),
    historyModalOverlay: document.getElementById('history-modal-overlay'),
    historyModalCloseBtn: document.getElementById('history-modal-close-btn'),
    generatedGamesModalOverlay: document.getElementById('generated-games-modal-overlay'),
    generatedGamesModalCloseBtn: document.getElementById('generated-games-modal-close-btn'),
    jogosGeradosModalDisplay: document.getElementById('jogos-gerados-modal-display'),
    copyGamesButtonModal: document.getElementById('copy-games-btn-modal'),
    assistenciaModalOverlay: document.getElementById('assistencia-modal-overlay'),
    assistenciaModalCloseBtn: document.getElementById('assistencia-modal-close-btn'),
    assistenciaModalTitle: document.getElementById('assistencia-modal-title'),
    mainTitle: document.getElementById('main-title'),
    authForms: document.getElementById('auth-forms'),
    loginForm: document.getElementById('login-form'),
    loginEmail: document.getElementById('login-email'),
    loginPassword: document.getElementById('login-password'),
    registerForm: document.getElementById('register-form'),
    registerName: document.getElementById('register-name'),
    registerEmail: document.getElementById('register-email'),
    registerPassword: document.getElementById('register-password'),
    registerSetupCode: document.getElementById('register-setup-code'),
    registerTermsAccepted: document.getElementById('register-terms-accepted'),
    openPrivacyTermsButton: document.getElementById('open-privacy-terms-btn'),
    privacyTermsModalOverlay: document.getElementById('privacy-terms-modal-overlay'),
    privacyTermsContent: document.getElementById('privacy-terms-content'),
    privacyTermsCloseButton: document.getElementById('privacy-terms-close-btn'),
    privacyTermsAcceptButton: document.getElementById('privacy-terms-accept-btn'),
    privacyTermsDismissButton: document.getElementById('privacy-terms-dismiss-btn'),
    guestAccessButton: document.getElementById('guest-access-btn'),
    accountPanel: document.getElementById('account-panel'),
    accountPlanBadge: document.getElementById('account-plan-badge'),
    accountUserName: document.getElementById('account-user-name'),
    accountUserEmail: document.getElementById('account-user-email'),
    accountUsage: document.getElementById('account-usage'),
    premiumPixButton: document.getElementById('premium-pix-btn'),
    adminUsersButton: document.getElementById('admin-users-btn'),
    navLoginButton: document.getElementById('nav-login-btn'),
    logoutButton: document.getElementById('logout-btn'),
    billingPixPanel: document.getElementById('billing-pix-panel'),
    adminUsersPanel: document.getElementById('admin-users-panel'),
    latestResultsGrid: document.getElementById('latest-results-grid'),
    dataStatusGrid: document.getElementById('data-status-grid'),
    dataStatusUpdatedAt: document.getElementById('data-status-updated-at'),
    updateDataButton: document.getElementById('update-data-btn'),
    generationModeSection: document.getElementById('generation-mode-section'),
    generationModeGrid: document.getElementById('generation-mode-grid'),
    selectedGenerationModeLabel: document.getElementById('selected-generation-mode-label'),
    premiumUpsellPanel: document.getElementById('premium-upsell-panel'),
    premiumUpsellButton: document.getElementById('premium-upsell-btn'),
    lotteryOptionGrid: document.getElementById('lottery-option-grid'),
    selectedLotteryName: document.getElementById('selected-lottery-name'),
    selectedLotteryMeta: document.getElementById('selected-lottery-meta'),
    historyModalTitle: document.getElementById('history-modal-title'),
    generatedGamesModalTitle: document.getElementById('generated-games-modal-title'),
    jogosGeradosMainDisplay: document.getElementById('jogos-gerados-main-display'),
    appFooter: document.getElementById('app-footer'),
    footerYear: document.getElementById('footer-year'),
    drawCalendarGrid: document.getElementById('draw-calendar-grid'),
};

export const lotteryColors = {
    megasena: {
        primary: '#209869',
        secondary: '#8FCBB3',
        readable: '#047857',
        readableDark: '#6EE7B7',
        border: '#059669',
        ball: '#047857',
        softBg: 'rgba(16, 185, 129, 0.14)',
        softBgDark: 'rgba(16, 185, 129, 0.16)',
        action: '#0F766E',
    },
    lotofacil: {
        primary: '#930089',
        secondary: '#C87FC3',
        readable: '#930089',
        readableDark: '#F0ABFC',
        border: '#A10096',
        ball: '#930089',
        softBg: 'rgba(147, 0, 137, 0.12)',
        softBgDark: 'rgba(217, 70, 239, 0.15)',
        action: '#930089',
    },
    quina: {
        primary: '#260085',
        secondary: '#927FC1',
        readable: '#4C1D95',
        readableDark: '#C4B5FD',
        border: '#5B21B6',
        ball: '#260085',
        softBg: 'rgba(91, 33, 182, 0.12)',
        softBgDark: 'rgba(139, 92, 246, 0.16)',
        action: '#260085',
    },
    diadesorte: {
        primary: '#C76A00',
        secondary: '#F4C56A',
        readable: '#92400E',
        readableDark: '#FBBF24',
        border: '#B45309',
        ball: '#B45309',
        softBg: 'rgba(180, 83, 9, 0.13)',
        softBgDark: 'rgba(245, 158, 11, 0.15)',
        action: '#B45309',
    },
};

export const lotteryDetails = {
    megasena: {
        name: 'Mega Sena',
        summary: '6 dezenas de 1 a 60',
        accent: '#157347',
    },
    lotofacil: {
        name: 'Lotofácil',
        summary: '15 dezenas de 1 a 25',
        accent: '#7A006F',
    },
    quina: {
        name: 'Quina',
        summary: '5 dezenas de 1 a 80',
        accent: '#1D006B',
    },
    diadesorte: {
        name: 'Dia de Sorte',
        summary: '7 dezenas de 1 a 31 + mês',
        accent: '#9A5200',
    },
};

export const state = {
    currentGeneratedGames: [],
    currentUser: null,
    selectedGenerationMode: 'normal',
};

export function selectedLotteryType() {
    return elements.lotterySelect.value;
}

export function selectedGenerationMode() {
    return state.selectedGenerationMode;
}

export function adjustableFontElements() {
    return [
        elements.mainTitle,
        elements.authGate,
        elements.topNav,
        elements.accountPlanBadge,
        elements.accountUsage,
        elements.latestResultsGrid,
        elements.dataStatusGrid,
        elements.dataStatusUpdatedAt,
        elements.generationModeSection,
        elements.selectedGenerationModeLabel,
        elements.premiumUpsellPanel,
        elements.lotteryOptionGrid,
        elements.selectedLotteryName,
        elements.selectedLotteryMeta,
        elements.lotterySelect,
        elements.numGamesInput,
        ...Array.from(document.querySelectorAll('label')),
        elements.modalTitle,
        elements.modalMessage,
        elements.successModalMessage,
        elements.historyModalTitle,
        elements.historicoArquivosLista,
        elements.historicoConteudoJogosWrapper,
        elements.assistenciaModalTitle,
        elements.jogosGeradosModalDisplay,
        elements.generatedGamesModalTitle,
        elements.footerYear,
        elements.drawCalendarGrid,
    ].filter(Boolean);
}
